//autogenerated
var x = 5;
console.log(x);
var greet = function () { return console.log('Hello'); };
greet();

// Because node is also js environment,
// Even node can't understand ts code
// So convert ts file to js file using transpiler
// Instead of powershell, use command prompt and transpile it
// It will auto generate .js file
